My second Doxygen test: Sensor Class Reference
Sensor Class Reference
Declaracion de clase padre Sensor.
#include <Sensor.h>
Public Member Functions
Sensor ()
Constructor de clase Sensor.
~Sensor ()
Destructor de clase Sensor.
void readSensorVal ()
Lectura de datos de Sensores.
Detailed Description
Declaracion de clase padre Sensor.
Definition at line 15 of file Sensor.h.
Constructor & Destructor Documentation
Sensor()
Sensor::Sensor ()
Constructor de clase Sensor.
Definition at line 4 of file Sensor.cpp.
 {}                //Constructor
~Sensor()
Sensor::~Sensor ()
Destructor de clase Sensor.
Definition at line 11 of file Sensor.cpp.
 {}               //Destructor
Member Function Documentation
readSensorVal()
void Sensor::readSensorVal ()
Lectura de datos de Sensores.
Returns
void
Definition at line 7 of file Sensor.cpp.
                           {           //Falta agregar esto
   std::cout << "Seeing data of Sensor..." << std::endl;
 }
Referenced by AirQ::readAirQ(), Humidity::readHumidity(), IlluminationLv::readIlluminationLv(), and Temperature::readTemp().
The documentation for this class was generated from the following files:
Sensor.h
Sensor.cpp