My second Doxygen test: User Class Reference
User Class Reference
Declaracion de clase User.
#include <User.h>
Public Member Functions
User (string &, string &)
Constructor de clase User.
~User ()
Destructor de clase User.
void setNif (string &)
Establece el NIF del usuario.
string getNif ()
Regresa el Nif del usuario.
void setname (string &)
Estable el nombre del usuario.
string getname ()
Regresa el nombre del usuario.
void verifyNif (bool)
Verifica si el NIF introducido es permitido.
void verifyUser (bool)
Verifica si el numero de usuario introducido es permitido.
bool authenticateUser ()
Verifica si el NIF y el name son validos.
bool operator< (User &)
Sobrecarga del User para comparar usuarios.
void escribir (string, string)
Escribe el fichero de Usuarios.
void leer ()
Lee el fichero de Usuarios.
Private Attributes
bool validate
string name
string nif
set< pair< string, string > > UserData
Friends
ostream & operator<< (ostream &, User &)
Detailed Description
Declaracion de clase User.
Definition at line 45 of file User.h.
Constructor & Destructor Documentation
User()
User::User (string & name, string & nif)
Constructor de clase User.
Parameters
Strings del Nombre y Nif del usuario
Definition at line 14 of file User.cpp.
{
     setNif(nif);
     setname(name);
 }
~User()
User::~User ()
Destructor de clase User.
Definition at line 21 of file User.cpp.
 {}
Member Function Documentation
authenticateUser()
bool User::authenticateUser ()
Verifica si el NIF y el name son validos.
Returns
permiso para proseguir a la interface o no
Definition at line 58 of file User.cpp.
{
     bool validate = false;
 //-----MODIFICACION: EXCEPCIONES-----
     try{
         if(UserData.find({name,nif}) == UserData.end()){
             throw InvalidUserException();
         }
         std::cout << "\nVALID USER" << endl;
         std::cout << "Loading..." << endl << endl;
         sleep(2);
         system("clear");
         validate = true;
         auto date = chrono::system_clock::now();
         time_t actual_time = chrono::system_clock::to_time_t(date);
         std::cout << "Accessed time: " << ctime(&actual_time);
         return validate;
     }
     catch(InvalidUserException& e){
         std::cout << endl << "The USER:" << name << " IS NOT VALID" << endl;
         validate = false;
         std::cout << "The NIF:" << nif << " DOESN'T EXIST" << endl << endl;
         validate = false;
         sleep(2);
         throw system("./main");
     }
     return validate;
 }
Referenced by main().
escribir()
void User::escribir (string name, string nif)
Escribe el fichero de Usuarios.
Parameters
String de name y nif del usuario
Returns
Fichero users.dat
Definition at line 118 of file User.cpp.
{
     ofstream fichero;
     fichero.open("users.dat", ios::app); //Abrir el archivo en modo escritura
     if (fichero.fail()){
         cout<<"Wasn't possible to open file...";
         exit(1);
     }
     if (UserData.find({name,nif}) == UserData.end()){
         cout << "New Registration Done Correctly!!"<< endl;
         fichero<< "Name " << name << " Nif " << nif << endl;
         fichero.close();
     }
     else{
         cout << "Name or NIF already exist" << endl;
     }
 }
Referenced by main().
getname()
string User::getname ()
Regresa el nombre del usuario.
Returns
string del nombre
Definition at line 39 of file User.cpp.
                     {
     return name;
 }
getNif()
string User::getNif ()
Regresa el Nif del usuario.
Returns
String del NIF
Definition at line 29 of file User.cpp.
                    {
     return nif;
 }
leer()
void User::leer ()
Lee el fichero de Usuarios.
Returns
Lectura del fichero users.dat
Definition at line 90 of file User.cpp.
                {
     ifstream fichero;
     string texto;
     fichero.open("users.dat", ios::in); //Abrir el archivo en modo escritura
     if (fichero.fail()){
         cout<<"Wasn't possible to open file...";
         exit(1);
     }
     while(!fichero.eof()){
         getline(fichero,texto);
         char delimeter = ' ';
         std::vector<std::string> tokens;
         std::string token;
         std::istringstream tokenStream(texto);
         while (getline(tokenStream, token, delimeter))
         {
             tokens.push_back(token);
         }
         if(tokens.size() > 3){
             UserData.insert({tokens.at(1),tokens.at(3)});
         }
     }
     fichero.close();
 }
Referenced by main().
operator<()
bool User::operator< (User & other)
Sobrecarga del User para comparar usuarios.
Parameters
Usuario a comparar
Returns
bool
Definition at line 138 of file User.cpp.
{
     return(this -> name > other.name);
 }
References name.
setname()
void User::setname (string & name)
Estable el nombre del usuario.
Parameters
String & del nombre
Returns
void
Definition at line 34 of file User.cpp.
{
     this -> name = name;
 }
setNif()
void User::setNif (string & nif)
Establece el NIF del usuario.
Parameters
String & del NIF
Returns
void
Definition at line 24 of file User.cpp.
{
     this -> nif = nif;
 }
verifyNif()
void User::verifyNif (bool validate)
Verifica si el NIF introducido es permitido.
Parameters
bool
Returns
Da la bienvenida al usuario o indica que no es correcto
Definition at line 44 of file User.cpp.
{
     if (validate == true){
         std::cout << "Employee with NIF: " << nif << endl;
     }
 }
Referenced by main().
verifyUser()
void User::verifyUser (bool validate)
Verifica si el numero de usuario introducido es permitido.
Parameters
bool
Returns
Da la bienvenida al usuario o indica que no es correcto
Definition at line 51 of file User.cpp.
{
     if(validate == true){
         std::cout << "Welcome User: " << name << endl;
     }
 }
Referenced by main().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & output, User & a) friend
Definition at line 142 of file User.cpp.
{
     cout << "[User's Name: " << a.getname() << "-- User's NIF: " << a.getNif() << "]" << endl;
     return output;
 }
Member Data Documentation
name
string User::name private
Definition at line 117 of file User.h.
Referenced by operator<().
nif
string User::nif private
Definition at line 118 of file User.h.
UserData
set<pair<string,string> > User::UserData private
Definition at line 119 of file User.h.
validate
bool User::validate private
Definition at line 116 of file User.h.
The documentation for this class was generated from the following files:
User.h
User.cpp